### ISSUE TITLE
Webpanel Update Page not finished

### ISSUE THREAD

**Issue by danialsaufi** [SourceMod-Store/store-webpanel#14]
![screenshot 1](https://cloud.githubusercontent.com/assets/9957629/5892296/ae05075c-a4f4-11e4-8022-9691a1c131dc.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/9957629/5892297/afa4aba8-a4f4-11e4-8de0-2e62103ebe53.png)
i got these problems what should i do?
and also when i typed !store or !shop in chat there wasnt any store pop up
so what did i do wrong?

**Comment by Arrow768** [comment]
If the errors only occur on this page, its because I had not time to finish the update page.

**Comment by highbot-core** [comment]
Pls finish this :D it's kinda nice to update through webpanel instead ftp

**Comment by Arrow768** [comment]
The WebPanel v2 supports updating via CLI --> Closed
