### ISSUE TITLE
Can't load user list and not working on in game

### ISSUE THREAD

**Issue by braak0405** [SourceMod-Store/store-webpanel#17]
<img src="http://i.imgur.com/4T8cqjS.png">
<img src="http://i.imgur.com/OjbhJdA.png">
<img src="http://i.imgur.com/Umxog3O.png">

"No categories are currnetly available" 

I install right but can't use store please help me

**Comment by Arrow768** [comment]
Please add a link to your webpanel.

**Comment by Arrow768** [comment]
Should be resolved with this commit
e21de026594bb69bde6ab0b0d8e122cac2eb8937

Dont forget to update to 1.2.9 when its out.
