### ISSUE TITLE
Only variable references should be returned by reference

### ISSUE THREAD

**Issue by nguyenbaodanh** [SourceMod-Store/store-webpanel#19]
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

**Comment by Arrow768** [comment]
Cant do much wich just the error message.
On what page did this error occur ?
Please add a link to the webpanel

**Comment by Arrow768** [comment]
No Response -> Closed
