### ISSUE TITLE
Update the Framework

### ISSUE THREAD

**Issue by Arrow768** [SourceMod-Store/store-webpanel#26]
The Store Webpanel is running on CodeIgniter 2.X

Eigther Update the Webpanel to CI 3.0 (released a few days ago)
or
Completely Change the Framework to Laravel

A Framework Change to Laravel would bring the following advantages:
* Installation and Updating can be done with a few cli commands
* Its possible to add a plugin-architecture to the webpanel

**Comment by Xerrion** [comment]
Also Laravels rounting does stuff more easy and is way faster.

**Comment by Arrow768** [comment]
The Framework has been changed to laravel.

See: http://github.com/SourceMod-Store/WebPanel-Core

This WebPanel is now feature complete and will receive bug fixes / updates until the new webpanel is stable
