### ISSUE TITLE
Please help =(

### ISSUE THREAD

**Issue by gasolino** [SourceMod-Store/store-webpanel#31]
Hi all, I have this problem with webpanel when import a file ".json". I have installed the trails on my css server, when I go choose the "trails.json" I have this error: 
![immagine](https://cloud.githubusercontent.com/assets/11800974/6994609/2eddf774-db20-11e4-87d6-0d69851e6496.png)
anyone can help me??
tnx all, sry for bad english.
hi

**Comment by Arrow768** [comment]
As mentioned here:
https://ellislab.com/forums/viewthread/205785/
This is a configuration issue.
Talk to your hoster about this problem
