### ISSUE TITLE
Users with unicode don't show

### ISSUE THREAD

**Issue by k0nan** [SourceMod-Store/store-webpanel#32]
If your nickname is containing unicode symbols you might not be able to receive credits (?)
They don't seem to be able to receive credits or to view credits/items they've previously earned when using another nick without unicode symbols.

Update: Users with unicode in their names shows as blanks in the webpanel:
Se images: 
![unicode not working](http://i.imgur.com/RoQKusI.png)
(The player name that does not show is: Weezy^ ♥Kejan♥Jejan♥Elias♥)

**Comment by Arrow768** [comment]
It works fine for me:
![unicode-screenshot](http://i.imgur.com/36JXfnW.png)

**Comment by k0nan** [comment]
Must have been fixed in some of the new store updates then. Maybe the Unicode wasn't sent to the sql properly before?

**Comment by Arrow768** [comment]
So you dont have this issue anymore with the new version ?

**Comment by k0nan** [comment]
The charset does not support some Unicode and swedish characters still.
http://imgur.com/EOLGprk

**Comment by Geekslomo** [comment]
I second that. Danish: --unstopable fighter-- (12 Ã¥r) 

"Ã¥r" should be "År".

**Comment by Arrow768** [comment]
Can you check if the name is displayed correctly, when accessing the db directly via phpmyadmin (or any other administration tool)

**Comment by Geekslomo** [comment]
It's the same when using phpmyadmin.

**Comment by Arrow768** [comment]
Then this is not a webpanel issue. (The Webpanel can only show whats in the db). 
I will talk to @Drixevel about this problem

**Comment by Geekslomo** [comment]
Roger - thank you.

**Comment by Arrow768** [comment]
Closed because its not a webpanel issue
