### ISSUE TITLE
Logging in has long lag before it loads the page after logged in.

### ISSUE THREAD

**Issue by Chdata** [SourceMod-Store/store-webpanel#39]
Dunno why. But it's an issue.

**Comment by Arrow768** [comment]
Are you still on the /auth/login page or have you already been redirected to / or /dashboard ?

**Comment by Chdata** [comment]
http://tf2data.com/sm/store/index.php/auth/login

It'll get stuck on a white page for a while before taking you to http://tf2data.com/sm/store/index.php/

If the password is wrong of course, it instantly clears the fields for you to type again, no white page.

**Comment by Arrow768** [comment]
But once you are at index.php/ you are logged in and can use the webpanel ?

**Comment by Chdata** [comment]
Yes it works fine.

**Comment by Arrow768** [comment]
Then this should be resolved with eef0393816250a5b3544df119a853d4a9f1e97e7
