### ISSUE TITLE
Error Number: 1146

### ISSUE THREAD

**Issue by zPow** [SourceMod-Store/store-webpanel#41]
I get this error when I try to login to my web panel:
>A Database Error Occurred
>
>Error Number: 1146
>
>Table 'tf2store.users' doesn't exist
>
>SELECT `email`, `username`, `email`, `id`, `password`, `active`, `last_login` FROM (`users`) WHERE >`email` = 'root' LIMIT 1
>
>Filename: X:\wamp\www\tf2store\system\database\DB_driver.php
>
>Line Number: 330

It occurs whenever I click the login button. I followed your installation instructions without any problems.
Here's a picture of what my database looks like:
![image](https://cloud.githubusercontent.com/assets/6785315/8386701/bf00df42-1c52-11e5-8486-df10f1bd9945.png)

**Comment by Arrow768** [comment]
You havnt read the installation tutorial
