### ISSUE TITLE
Show transaction-log in webpanel

### ISSUE THREAD

**Issue by k0nan** [SourceMod-Store/store-webpanel#42]
There would be awesome if you could see a transationlog (like the one stored locally in sourcemod/logs/store/info, but with purchaselogs as well) for each player in the webpanel on the users -> Manage page
Update: Timestamp when purchased on each item that is in a users storage on the webpanel would be amazing.

Right now some users report that credits have gone missing. Sometimes during gifting. There is impossible for me to check if the user bought any items for the credits or if they've gone missing somehow.

**Comment by Arrow768** [comment]
There wont be new features for the old WebPanel.
But something like that is already planned for the new Webpanel.

See SourceMod-Store/WebPanel-Core#11
