### ISSUE TITLE
Redeem Points issue

### ISSUE THREAD

**Issue by iphonerestore** [SourceMod-Store/store-webpanel#45]
Hi,
I can't seem to figure out what's going on with my WebPanel but it turns out I'm getting an SQL error when I go to the Redeem section in the backend.

Here is the error as follows
```
A Database Error Occurred

Error Number: 1146
Table 'waffleti_store.store_redeem_codes' doesn't exist

SELECT * FROM (`store_redeem_codes`)
Filename: /home/waffletime/public_html/shop/models/redeem_model.php

Line Number: 29
```
It will be great if you can provide some support for this.

**Comment by Arrow768** [comment]
You have to follow the installation instructions [in this post](https://forums.alliedmods.net/showpost.php?p=2239196&postcount=167) in the webpanel release thread
