### ISSUE TITLE
Seeing who has bought a certain item can skip including some users.

### ISSUE THREAD

**Issue by Chdata** [SourceMod-Store/store-webpanel#46]
If you go to manage items, and click "Times Bought", you're taken to a list of all the users who have bought the item.

However, from that list I have one user who has bought the item, and does not appear in the list above.

If I go to that user's profile in store and look at his items, he does indeed have the item according to his "Items" tab, and their item works in-game.

Edit: Shortly after I noticed my TF2 server was stalling for a bit on map changes and every time something database related happen the game would lag-freeze for a few seconds. The server's fine now. I'll check the webpanel later.

**Comment by Arrow768** [comment]
The webpanel can only show whats in the database.
If something isnt in the db its not shown.

And I think thats what happened here.
