### ISSUE TITLE
No Categories are currently available.

### ISSUE THREAD

**Issue by Bonkorn** [SourceMod-Store/store-webpanel#48]
I added this line on database,cfg
```
	"store"
	{
		"driver"			"mysql"
		"host"				"localhost"
		"database"			"store"
		"user"				"root"
		"pass"				""
	}
```
backend.cfg
```
	"base_url"					"http://localhost/store"
```
It stores player credits but No Categories are currently available.
![](http://i.imgur.com/jv1FSac.jpg)
![](http://i.imgur.com/Uqt5czd.jpg)
I have created Categories by using import json
![](http://i.imgur.com/RiPzflB.jpg)

**Comment by Arrow768** [comment]
Thats Problem with the store plugin.
The WebPanel can only add the data to the database.
If the data is in the DB, its up to the store plugin to display it.

**Comment by Bonkorn** [comment]
Nvm, It's fixed because i didin't add smjansson.ext extensions.
