### ISSUE TITLE
Expire Date

### ISSUE THREAD

**Issue by Bonkorn** [SourceMod-Store/store-webpanel#49]
What's the format of expire date?
![](http://i.imgur.com/mXZslJl.jpg)
![](http://i.imgur.com/Q9EGOHl.jpg)
Can you show me a example of 25th December 2015 8:40PM
I saw this thread but I don't know it clearly https://github.com/SourceMod-Store/store-webpanel/issues/18

**Comment by Arrow768** [comment]
2015-12-25 08:40:00
YYYY-MM-DD

You should use the Version 1.2.11 that has just been released.
(It fixes a bug in the redeem system.
