### ISSUE TITLE
User page not loading users

### ISSUE THREAD

**Issue by erwinquek** [SourceMod-Store/store-webpanel#50]
It shows "processing data from server" - does not show user list.

Is there a limit as to how many users exist in database?  Other pages loads fine.

**Comment by Arrow768** [comment]
Check the logs of the webpanel for errors then post them on gist.github.com and link them here.

**Comment by erwinquek** [comment]
Log from Web server:-
xxx.xxx.xxx.xxx - - [24/Dec/2015:09:26:50 +0800] "GET /items/index.php/users HTTP/1.0" 200 6433
xxx.xxx.xxx.xxx - - [24/Dec/2015:09:26:51 +0800] "GET /items/index.php/users/server_process?sEcho=1&iColumns=5&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=false&_=1450920411188 HTTP/1.0" 500 -

Used Webpanel 1.2.10, upgraded 1.2.12 - same results.  Store version 1.2 Final - working fine on game servers.

**Comment by erwinquek** [comment]
I faced the issue after changing host.  Resolved it by installing:-
php-bcmath
php-mbstring

Works fine now with 138K+ users.
