### ISSUE TITLE
Problem with data base 

### ISSUE THREAD

**Issue by kubekow** [SourceMod-Store/store-webpanel#51]
When i logged in to the control panel i have this error 

A Database Error Occurred

Error Number: 1146

Table 'csgo.users' doesn't exist

SELECT `email`, `username`, `email`, `id`, `password`, `active`, `last_login` FROM (`users`) WHERE `email` = 'admin@admin.com' LIMIT 1

Filename: /var/www/sklepcs/models/ion_auth_model.php

Line Number: 866

but i import befor msql

**Comment by Arrow768** [comment]
Read the installation tutorial.
Especially the section about the ion_auth.sql
