### ISSUE TITLE
Data Table Warning

### ISSUE THREAD

**Issue by adma23** [SourceMod-Store/store-webpanel#53]
**Update update : I left the json there for ~30 minutes and it imported. I feel dumb. But the Users -> Manage problem still persists.**

**Update : did a fresh install and used PHP 5.4 and now I don't get the error. Only problems I have is that I cannot import json of the trails (filesize?) and that Users -> Managers doesn't load up anything.**

![Image of Stuff](http://i.imgur.com/oQv0DcK.png)

I have recently installed store on my server and its working fine, but on the web panel when I go to Users -> Manage I get an error that says "DataTables warning (table id = 'manageUsers'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error."

![Image of Error](http://i.imgur.com/dNEMRCq.png)

Additionally, I can't seem to import any json files using the webpanels json importer. Once import is clicked, it just loads and doesn't stop.

**Comment by Arrow768** [comment]
Usually this (Datatables json error) happens when a php module is missing.
Install the firefox plugin firebug and check the requests.
If you switch to the html view for the datatables json request you should see why it fails.
