### ISSUE TITLE
Store webpanel cant import .json file

### ISSUE THREAD

**Issue by sword134** [SourceMod-Store/store-webpanel#54]
I get this when trying to import a .json file:

https://gyazo.com/811ed9374bc8411e131af56d1d1dba67

It worked fine before i reinstalled the webpanel

**Comment by sword134** [comment]
Bump

**Comment by Arrow768** [comment]
Read the [F.A.Q.](https://forums.alliedmods.net/showthread.php?p=2070713#post2070713) before asking questions.
A lot of them are answered there.

**Comment by sword134** [comment]
Nothing in the help under issue 1054 helped. So no reason to close the thread.
