### ISSUE TITLE
Can't find "store_users"

### ISSUE THREAD

**Issue by whipstxr** [SourceMod-Store/store-webpanel#56]
So i was trying to install the webpanel and this appears. I can't find "store_users" anywhere + it doesn't add from the import.
`Error Number: 1146

Table 'chemical_store.store_users' doesn't exist

SELECT \* FROM (`store_users`) ORDER BY `credits` desc LIMIT 5

Filename: /home/chemical/public_html/csgostore/models/users_model.php

Line Number: 29`

**Comment by Arrow768** [comment]
Please read the requirements area in the installation tutorial on the wiki and verify that you have met all requirements.

This usually happens if one of the requirements is not met

**Comment by whipstxr** [comment]
Looks like everything is should as it should be

**Comment by whipstxr** [comment]
So i contacted my host and this is what he said:
"Hello ****,

While I am not familiar with this particular software, I do see an issue when comparing the error you've received to the MySQL Database. The error message is looking for '*******__store.store_users', however your database contents are '**_*****_store.users' which does not match. As such, the query being performed is unable to properly fetch the desired information.

This appears to be a conflict between the web code and the SQL file provided. I would advise contacting the developer once more and pointing this out, where this is an issue he will need to resolve."

**Comment by Arrow768** [comment]
Taken directly from the requirements:
_Access to the Store Database from the Webspace (webpanel db = store db)_

Have you imported the store tables into the same database ?

**Comment by Nobody-x** [comment]
Hi, this happen when you install the webpanel before the store plugin, so plugin's tables don't exists.
