### ISSUE TITLE
Blank page when config.php exits

### ISSUE THREAD

**Issue by lauritslenz** [SourceMod-Store/store-webpanel#58]
Hi, i have a quick question. I think i located the error as being the config.php. When i dont have a config.php or rename it to config[something].php i get an error message on the site. It says that it is missing a configuaration file. But atleast there is somehting other then a blank screen. Thanks in advance

**Comment by Arrow768** [comment]
Verify that you have met all the requirements
https://github.com/SourceMod-Store/store-webpanel/wiki/Installation-of-the-WebPanel#requirements
