### ISSUE TITLE
Code/Redeem System seems to be missing

### ISSUE THREAD

**Issue by LordMephisto94** [SourceMod-Store/store-webpanel#62]
As stated in the title every time i try to access the "redeem" section of the webpanel im meet with an SQL error. Is this something that i have to create myself? I've imported all the SQL files stated in the tutorial.
`A Database Error Occurred

Error Number: 1146

Table 'surfstore.store_redeem_codes' doesn't exist

SELECT \* FROM (`store_redeem_codes`)

Filename: C:\xampp\htdocs\sites\RAusG\store\system\database\DB_driver.php

Line Number: 330`

**Comment by Arrow768** [comment]
You havnt imported the required sql file.

**Comment by LordMephisto94** [comment]
But if you read the post i have..... I've imported both SQL files that were mentioned in the tutorial...

**Comment by Arrow768** [comment]
Redeem system needs the ones labeled "128_redeem_tables.sql"

**Comment by LordMephisto94** [comment]
Thank you. that is not mentioned within the Tutorial...
