### ISSUE TITLE
NGINX not supported?

### ISSUE THREAD

**Issue by ghost** [SourceMod-Store/store-webpanel#68]
I can't see anything immediate that would make this "non-nginx compatible?" Nor do i see anything thats "Apache specific".

Please elaborate? Writing a statement that it's not "nginx compatible, use at your own risk" is extremely vague. As something specific needs to be wrong / used if its only compatible with Apache

**Comment by Arrow768** [comment]
It doesnt say that nginx is not compatible.
It sais that its not supported. Which means that I have not tested it and therfore can not say if its going to work and if its not working I cant provide support for it.

**Comment by ghost** [comment]
No offense, but either your a level one developer that barely know what your doing, or it works with nginx without any problems what so ever.

For a PHP script to not work with nginx by default, you either have to use mod_rewrite (htaccess) or anything Apache specific. If you do, you would know when you make the script.

Writing the message you have make it seem like nginx actually isnt supported or will work, like a previous issue (#65) where someone gets a 404 page and take your nginx message seriously and gives up, and worst case scenario, switches from awesome nginx to horrible apache just to use this simple script.

**Comment by ghost** [comment]
Update:

if anyone else is having issues / wondering, then the standard CodeIgniter (Which this entire app basically is) setup guide for Nginx will work perfectly fine.

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

Suggest that you remove your notification and include that link instead.

**PS!** It's a pain to setup in a subfolder, recommended to host it on a root domain / subdomain if your not to familiar with nginx. The standard guide (Link above) will work without problems if used on the root domain.

**Comment by Dragonissa** [comment]
> Update:
> 
> if anyone else is having issues / wondering, then the standard CodeIgniter (Which this entire app basically is) setup guide for Nginx will work perfectly fine.
> 
> https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/
> 
> Suggest that you remove your notification and include that link instead.
> 
> **PS!** It's a pain to setup in a subfolder, recommended to host it on a root domain / subdomain if your not to familiar with nginx. The standard guide (Link above) will work without problems if used on the root domain.

Thanks a lot, it worked perfectly fine.
